#!/usr/bin/env perl

# ダミーデータを投入する

use strict;
use warnings;
use utf8;
use lib $ENV{MT_HOME} ? "$ENV{MT_HOME}/lib" : 'lib';

use Getopt::Long qw(:config posix_default no_ignore_case gnu_compat);
use Data::Dumper;
use MT;

binmode(STDOUT, ":utf8");

GetOptions(
    'blog_id=s'   => \my $blog_id,
    'name=s'      => \my $author_name,
    'entry_num=i' => \my $entry_num,
);

unless (defined $blog_id) {
    die "ブログIDを指定してください。\n";
}

unless (defined $author_name) {
    die "投稿者名を指定してください。\n";
}

my $mt = MT->new() or die MT->errstr;
my $blog = MT::Blog->load({
    id => $blog_id,
}) or die "ブログが見つかりませんでした。[ID: " . $blog_id . "]\n";

my $author = MT::Author->load({
    name => $author_name,
}) or die "投稿者が見つかりませんでした。[Name: " . $author_name . "]\n";

my $options = {
    entry_num => $entry_num // 1,
};

require Faker::Cmd;
Faker::Cmd::main($blog, $author, $options);
exit;

1;
