#!/usr/bin/env perl

# ダミーデータを投入する
# Options
#   blog_id : 対象のブログIDを指定します
#   name    : 投稿ユーザ名を指定します
#   num     : 投稿するエントリー数を指定します
#   perday  : 1日に登録する件数を指定します
# Ex) ブログID 1のブログに hoge ユーザで 10000件のエントリーを 1日に10件ずつ入れる場合
#   tools/faker --blog_id=1 --name=hoge --num=10000 --perday=10

use strict;
use warnings;
use utf8;
use lib $ENV{MT_HOME} ? "$ENV{MT_HOME}/lib" : 'lib';

use Getopt::Long qw(:config posix_default no_ignore_case gnu_compat);
use Data::Dumper;
use MT;

binmode(STDOUT, ":utf8");

GetOptions(
    'blog_id=s'   => \my $blog_id,
    'name=s'      => \my $author_name,
    'num=i'       => \my $entry_num,
    'perday=i'    => \my $entry_per_day,
);

unless (defined $blog_id) {
    die "ブログIDを指定してください。\n";
}

unless (defined $author_name) {
    die "投稿者名を指定してください。\n";
}

my $mt = MT->new() or die MT->errstr;
my $blog = MT::Blog->load({
    id => $blog_id,
}) or die "ブログが見つかりませんでした。[ID: " . $blog_id . "]\n";

my $author = MT::Author->load({
    name => $author_name,
}) or die "投稿者が見つかりませんでした。[Name: " . $author_name . "]\n";

my $options = {
    entry_num => $entry_num // 1,
    entry_per_day => $entry_per_day // 1,
};

require Faker::Cmd;
Faker::Cmd::main($blog, $author, $options);
exit;

1;
